# Generated by Django 4.2.6 on 2023-10-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=127, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('image', models.ImageField(blank=True, upload_to='uploads/pages/%Y-%m-%d/', verbose_name='image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('meta_title', models.CharField(blank=True, max_length=127, verbose_name='meta_title')),
                ('meta_keywords', models.CharField(blank=True, max_length=127, verbose_name='meta_keywords')),
                ('meta_description', models.TextField(blank=True, max_length=127, verbose_name='meta_description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('is_header', models.BooleanField(default=True)),
                ('is_footer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPages',
            fields=[
                ('pagesbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.pagesbasemodel')),
            ],
            options={
                'verbose_name': 'Доп.Страницы',
                'verbose_name_plural': 'Доп.Страницы',
            },
            bases=('website.pagesbasemodel',),
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('pagesbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.pagesbasemodel')),
                ('childrens', models.ManyToManyField(blank=True, related_name='childrens_pages', to='website.subpages', verbose_name='childrens_pages')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницы',
            },
            bases=('website.pagesbasemodel',),
        ),
    ]
