# Generated by Django 4.2.6 on 2023-10-30 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='childrens',
        ),
        migrations.AddField(
            model_name='subpages',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='website.pages', verbose_name='parent_category'),
        ),
    ]
