# Generated by Django 5.0 on 2023-12-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_alter_productcolor_title'),
        ('ecommerce', '0001_initial'),
        ('product', '0011_remove_products_product_color_products_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrates',
            options={'ordering': ('id',), 'verbose_name': 'Курс валюты', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_charge', models.PositiveSmallIntegerField(verbose_name='Наша наценка, %')),
                ('discount_real', models.PositiveSmallIntegerField(verbose_name='Скидка производителя, %')),
                ('discount_fake', models.PositiveSmallIntegerField(verbose_name='Фейковая скидка, %')),
                ('parent_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='characteristics.productbrand', verbose_name='parent_country_brand')),
                ('parent_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ecommerce.currencyrates', verbose_name='parent_country_brand')),
                ('parent_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.series', verbose_name='parent_country_series')),
            ],
        ),
    ]
