# Generated by Django 5.0 on 2023-12-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_order_alter_course_parent_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=47, verbose_name='город клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=47, verbose_name='email клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.TextField(verbose_name='Заказ'),
        ),
    ]
