# Generated by Django 4.2.6 on 2023-11-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_series_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='parent_series', to='product.categories', verbose_name='parent_series'),
            preserve_default=False,
        ),
    ]
