# Generated by Django 4.2.6 on 2023-11-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_images_options_alter_name_options'),
        ('product', '0008_alter_products_product_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_code_color',
            field=models.SmallIntegerField(default=1, help_text='Данный код объединяет товар по цвету', verbose_name='Код объединения товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='gallery',
            field=models.ForeignKey(blank=True, help_text='Только для 3D галерей', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_gallery', to='gallery.name', verbose_name='series_gallery'),
        ),
    ]
