# Generated by Django 4.2.6 on 2023-11-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_products_product_code_color_alter_products_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_code_color',
            field=models.CharField(blank=True, help_text='Данный код объединяет товар по цвету', max_length=30, verbose_name='Код объединения товара'),
        ),
    ]
