# Generated by Django 4.2.5 on 2023-10-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=256, verbose_name='site name')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone1', models.PositiveSmallIntegerField(default=0, verbose_name='phone1')),
                ('phone2', models.PositiveSmallIntegerField(default=0, verbose_name='phone2')),
                ('facebook', models.CharField(blank=True, max_length=256, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, max_length=256, verbose_name='twitter')),
                ('instagram', models.CharField(blank=True, max_length=256, verbose_name='instagram')),
                ('linkedin', models.CharField(blank=True, max_length=256, verbose_name='linkedin')),
                ('youtube', models.CharField(blank=True, max_length=256, verbose_name='youtube')),
                ('vk', models.CharField(blank=True, max_length=256, verbose_name='vk')),
            ],
            options={
                'verbose_name': 'Constant',
                'verbose_name_plural': 'Constants',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='uploads/slider/', verbose_name='image')),
                ('button_title', models.CharField(blank=True, max_length=64, verbose_name='button title')),
                ('button_slug', models.CharField(blank=True, max_length=256, verbose_name='button slug')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
