# Generated by Django 4.2.5 on 2023-10-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constants',
            options={'verbose_name': 'Константа', 'verbose_name_plural': 'Константы'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AddField(
            model_name='constants',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/logo/', verbose_name='logo'),
        ),
    ]
