# Generated by Django 4.2.5 on 2023-10-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0003_alter_constants_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='phone1',
            field=models.CharField(blank=True, max_length=24, verbose_name='phone1'),
        ),
        migrations.AlterField(
            model_name='constants',
            name='phone2',
            field=models.CharField(blank=True, max_length=24, verbose_name='phone2'),
        ),
    ]
