# Generated by Django 4.2.6 on 2023-10-31 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('is_3d', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=127, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='uploads/gallery/%Y-%m-%d/', verbose_name='image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_gallery', to='gallery.name', verbose_name='parent_gallery')),
            ],
        ),
    ]
