# Generated by Django 4.2.6 on 2023-10-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('parent',), 'verbose_name': 'Картинки', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ('title',), 'verbose_name': 'Имя галереи', 'verbose_name_plural': 'Имя галереи'},
        ),
    ]
