# Generated by Django 4.2.6 on 2023-11-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/characteristics/%Y-%m-%d/', verbose_name='image'),
        ),
    ]
